{% set version = "4.4.4" %}
package:
  name: netcdff
  version: {{ version }}

source:
  - url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
 
requirements:
  build:
    - gcc
    - make
    - libnetcdf
    - hdf5
  run:
    - libnetcdf
    - hdf5
