{% set version = "4.4.4" %}
package:
  name: netcdff-ng
  version: {{ version }}

source:
  - url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
 
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - libnetcdf                   # ng
    - hdf5
  run:
    - libnetcdf                   # ng
    - hdf5

